### PR TITLE
Add code linters and remove dead code

### PR DESCRIPTION
**Pull request by aaaandrzej**
This addresses some of the points mentioned in [#33]:
- Fix flake8 errors
- removing dead code

Black should format the code in a way acceptable by `flake8` when using current config. `make lint-fix` to be run against this branch once #41 is merged to avoid too many conflicts. 

I probably won't be able to fix points 3-5 very soon so the question is if we want to merge it separately or whether the PR should fix all of the [#33] issues

### CODE REVIEW

**Comment by ClasherKasten** [comment]
Some little things:
- I would like to stick to single quotes instead of switching to double quotes
- Makefile is an idea, but setting up [pre-commit](https://pre-commit.com/) would be a better option in my opinion

**Comment by aaaandrzej** [comment]
Single quotes seem doable, there's `axblack` fork of `black` that does that, I can add it easily. I won't be able to help with pre-commit hooks soon though, I'm afraid, as it looks like quite a big task itself. Would you accept a PR with formatting fixed, flake8 happy and dead code removed, or would you rather prefer for someone else to complete the whole [#33] at one go?

**Comment by aaaandrzej** [comment]
Note on the PR closure - I underestimated merge conflicts and decided to force push which closed this PR automatically, but my previous comment should be still valid.

**Comment by ClasherKasten** [comment]
> Would you accept a PR with formatting fixed, flake8 happy and dead code removed, or would you rather prefer for someone else to complete the whole [https://github.com/marcusbuffett/command-line-chess/issues/33] at one go?

Every single step towards better code quality is welcome. So yes, I would also merge a PR with formatting corrected, happy flake8 and dead code removed.

**Pull request closed without merging**
